#ifndef TASK_TYPE_H
#define TASK_TYPE_H

// 往复机相关
const int32 HT_TASK_GETDAUINFO				 = 1;
const int32 HT_TASK_GETDAUSETUP				 = HT_TASK_GETDAUINFO + 1;
const int32 HT_TASK_UPDATEBASICSETUP		 = HT_TASK_GETDAUINFO + 2;
const int32 HT_TASK_UPDATESOCKETSETUP		 = HT_TASK_GETDAUINFO + 3;
const int32 HT_TASK_UPDATECONDITIONSETUP	 = HT_TASK_GETDAUINFO + 4;
const int32 HT_TASK_UPDATETHRESHOLDSETUP	 = HT_TASK_GETDAUINFO + 5;
const int32 HT_TASK_ACTIVATESOCKET           = HT_TASK_GETDAUINFO + 6;
const int32 HT_TASK_FORBIDSOCKET		     = HT_TASK_GETDAUINFO + 7;
const int32 HT_TASK_UPDATECARDDRIVER         = HT_TASK_GETDAUINFO + 8;
const int32 HT_TASK_UPDATE_VARTHRESHOLD		 = HT_TASK_GETDAUINFO + 9;
const int32 HT_TASK_STATVARTHRESHOLD	     = HT_TASK_GETDAUINFO + 10; // 门限自学习任务 机组任务
const int32 HT_TASK_GATHERRINGBUFFER		 = HT_TASK_GETDAUINFO + 11;

// 风电机相关
const int32 HT_TASK_DOWNLOADFILETOFDAU       = 100; // 服务端向FAS下载程序文件
const int32 HT_TASK_GATHERVIBWAVE			 = HT_TASK_DOWNLOADFILETOFDAU  + 1; // 获取振动通道波形
const int32 HT_TASK_GATHERKEYWAVE			 = HT_TASK_DOWNLOADFILETOFDAU  + 2; // 获取键相波形
const int32 HT_TASK_GATHERVIBSERIESWAVE		 = HT_TASK_DOWNLOADFILETOFDAU  + 3; // 获取振动通道连续波形  
const int32 HT_TASK_CANCELGATHERSERIESWAVE   = HT_TASK_DOWNLOADFILETOFDAU  + 4;	// 要求取消对某振动通道在一段时间内的连续波形采集 
const int32 HT_TASK_UPDATEFASSETUP			 = HT_TASK_DOWNLOADFILETOFDAU  + 5;	// 服务端向FAS下载设置信息
const int32 HT_TASK_GETFASSETUP	             = HT_TASK_DOWNLOADFILETOFDAU  + 6; // 服务端向FAS要FAS设置信息



const int32 RC_TASK_SYNCSETUP					= 1000; // 上下级服务器同步机组设置
const int32 RC_TASK_SYNCOVERVIEW				= 1001;	// 上下级服务器同步机组总貌图
#endif
